import { useEffect, useState } from "react";
import "@/App.css";
import { ArrowRight, Check, ChevronDown, Circle, Code2, Database, Download, ExternalLink, FolderOpen, Gauge, Menu, Play, Server, ShieldCheck, Sparkles, Terminal, X, Zap } from "lucide-react";
import { DOWNLOAD_URL, PRODUCT } from "@/config";

const navItems = [
  ["Overview", "overview"], ["Features", "features"], ["Documentation", "documentation"], ["Requirements", "requirements"], ["FAQ", "faq"],
];
const features = [
  { icon: Code2, number: "01", title: "Portable PHP Runtime", text: "A clean PHP 8.4 runtime, installed directly from MiniDev and kept isolated from your system.", items: ["PHP 8.4", "Install directly from MiniDev", "No system-wide PHP", "Isolated runtime storage"] },
  { icon: Server, number: "02", title: "Portable MySQL", text: "MySQL 8.4 LTS that starts when you need it, without creating a Windows Service.", items: ["MySQL 8.4 LTS", "Install and initialize", "Start / stop on demand", "No Windows Service"] },
  { icon: FolderOpen, number: "03", title: "Laravel Project Manager", text: "Bring existing Laravel projects into one focused place to start, stop, and open them.", items: ["Add existing projects", "Start and stop projects", "Open in browser", "Runtime on demand"] },
  { icon: Database, number: "04", title: "Database Explorer", text: "Browse the databases and tables behind your local work, then view and manage records.", items: ["Browse databases", "Browse tables", "View records", "Create / update / delete rows"] },
  { icon: Terminal, number: "05", title: "SQL Tools", text: "Keep everyday database work close to the project with a focused set of SQL tools.", items: ["SQL editor", "Database import", "Database export", "MySQL dump support"] },
  { icon: Zap, number: "06", title: "Process Lifecycle", text: "MiniDev keeps its footprint small by cleaning up owned child processes when you are done.", items: ["Services stop when unused", "Owned process cleanup", "No unnecessary background work"] },
];
const faqs = [
  ["Do I need PHP installed on Windows?", "No. MiniDev manages its own portable PHP runtime."],
  ["Do I need MySQL installed on Windows?", "No. MiniDev can install and manage its own MySQL runtime."],
  ["Does MiniDev install MySQL as a Windows Service?", "No. MySQL is controlled directly by MiniDev."],
  ["Will MiniDev change my system PATH?", "No. MiniDev-owned runtimes are isolated from your global PATH."],
  ["Can I use an existing Laravel project?", "Yes. Existing Laravel projects can be added to the project manager."],
  ["Does uninstalling MiniDev automatically delete my databases?", "Always back up important databases before uninstalling or testing beta versions."],
  ["Is MiniDev production ready?", "MiniDev is currently Beta and intended for local development environments."],
];

const DownloadButton = ({ children, className = "" }) => <a data-testid="download-beta-button" className={`button button-primary ${className}`} href={DOWNLOAD_URL} aria-label="Download MiniDev Beta">{children || <>Download MiniDev Beta <Download size={16} /></>}</a>;

function App() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [activeFaq, setActiveFaq] = useState(0);
  useEffect(() => {
    document.title = "MiniDev — Lightweight Local Development for Windows";
    const description = document.querySelector('meta[name="description"]');
    if (description) description.setAttribute("content", "MiniDev is a lightweight Windows local development environment for PHP, MySQL, Laravel projects and database management.");
    [["og:title", "MiniDev — Lightweight Local Development for Windows"], ["og:description", "A lightweight Windows local development environment with portable PHP, MySQL, Laravel project management, and database tools."]].forEach(([property, content]) => {
      let tag = document.querySelector(`meta[property="${property}"]`);
      if (!tag) { tag = document.createElement("meta"); tag.setAttribute("property", property); document.head.appendChild(tag); }
      tag.setAttribute("content", content);
    });
  }, []);
  const closeMenu = () => setMobileOpen(false);
  return <div className="site-shell">
    <header className="navbar" data-testid="site-navbar"><a href="#overview" className="brand" data-testid="brand-link" onClick={closeMenu}><span className="brand-mark"><span /></span><span>MiniDev</span></a>
      <nav className={mobileOpen ? "nav-links is-open" : "nav-links"} aria-label="Main navigation">{navItems.map(([label, id]) => <a data-testid={`nav-${id}-link`} key={id} href={`#${id}`} onClick={closeMenu}>{label}</a>)}<DownloadButton>Download Beta <Download size={15} /></DownloadButton></nav>
      <button className="menu-toggle" data-testid="mobile-menu-button" aria-label={mobileOpen ? "Close menu" : "Open menu"} aria-expanded={mobileOpen} onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X /> : <Menu />}</button>
    </header>

    <main>
      <section className="hero section-grid" id="overview"><div className="hero-copy reveal"><div className="eyebrow"><span className="status-dot" /> Beta v0.1.0</div><h1>Local Development,<br /><em>Without the Bloat.</em></h1><p className="hero-lede">MiniDev is a lightweight Windows local development environment for PHP, MySQL, Laravel projects, and database management — with services that only run when you need them.</p><div className="hero-actions"><DownloadButton /><a className="button button-secondary" data-testid="documentation-hero-link" href="#documentation">View Documentation <ArrowRight size={16} /></a></div><div className="download-meta" data-testid="hero-download-details"><span><strong>MiniDev {PRODUCT.version}</strong><small>Windows x64</small></span><i /><span><strong>Installer ±3.8 MB</strong><small>{PRODUCT.installer}</small></span></div></div>
        <div className="hero-visual reveal reveal-delay"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="app-window" data-testid="app-mockup"><div className="window-bar"><span className="window-dots"><i /><i /><i /></span><span className="window-title">MiniDev <b>LOCAL</b></span><span className="window-controls">— □ ×</span></div><div className="window-body"><aside><div className="mini-logo"><span /></div><span className="side-active"><Gauge size={14} /> Overview</span><span><FolderOpen size={14} /> Projects</span><span><Database size={14} /> Database</span><span><Server size={14} /> Runtimes</span><div className="side-bottom"><span><ShieldCheck size={14} /> Settings</span></div></aside><div className="app-content"><div className="app-heading"><div><small>GOOD MORNING</small><h3>Workspace overview</h3></div><span className="online-pill"><Circle size={7} fill="currentColor" /> Ready</span></div><div className="runtime-card"><div className="runtime-icon"><Code2 size={18} /></div><div><small>PHP RUNTIME</small><strong>PHP 8.4.25</strong></div><span className="installed"><Check size={12} /> Installed</span></div><div className="mock-grid"><div className="mock-card"><small>PROJECTS</small><strong>03</strong><span>Across workspace</span></div><div className="mock-card"><small>SERVICES</small><strong>01</strong><span><i className="live-dot" /> Running now</span></div></div><div className="project-row"><div><FolderOpen size={15} /><span><b>laravel-store</b><small>~/Projects/laravel-store</small></span></div><button data-testid="mockup-start-project-button" aria-label="Start laravel-store"><Play size={12} fill="currentColor" /> Start</button></div></div></div></div><div className="visual-caption"><span><Sparkles size={13} /> Focused by design</span><span>Windows x64</span></div></div>
      </section>

      <section className="intro section-grid" id="intro"><div className="section-heading reveal"><span className="kicker">01 / THE IDEA</span><h2>Built to stay<br /><em>out of your way.</em></h2></div><div className="intro-copy reveal reveal-delay"><p>MiniDev is designed as a local development environment for Windows that respects your machine. Install the runtimes you need, start services when work begins, and keep everything else quiet.</p><div className="intro-points"><div><Zap size={18} /><span><b>Lightweight</b><small>Services run on demand.</small></span></div><div><ShieldCheck size={18} /><span><b>Portable Runtime</b><small>Managed without changing global Windows configuration.</small></span></div><div><FolderOpen size={18} /><span><b>Simple Project Management</b><small>Add, start, stop, and open Laravel projects in one place.</small></span></div><div><Database size={18} /><span><b>Integrated Database Tools</b><small>Manage databases without a separate database app.</small></span></div></div></div></section>

      <section className="features section-grid" id="features"><div className="section-heading reveal"><span className="kicker">02 / CAPABILITIES</span><h2>Everything your<br /><em>local stack needs.</em></h2><p>A focused toolkit for the work between opening an editor and shipping a feature.</p></div><div className="feature-grid">{features.map(({ icon: Icon, number, title, text, items }, i) => <article className={`feature-card reveal reveal-delay-${Math.min(i % 3 + 1, 3)}`} data-testid={`feature-card-${number}`} key={title}><div className="feature-top"><span className="feature-icon"><Icon size={20} /></span><span>{number}</span></div><h3>{title}</h3><p>{text}</p><ul>{items.map(item => <li key={item}><Check size={14} />{item}</li>)}</ul></article>)}</div></section>

      <section className="why section-grid" id="why"><div className="section-heading reveal"><span className="kicker">03 / THE DIFFERENCE</span><h2>Everything you need.<br /><em>Nothing running unnecessarily.</em></h2></div><div className="concepts reveal reveal-delay"><div className="concept"><span>01</span><h3>Traditional local stacks</h3><p>Install everything and keep multiple services available.</p></div><ArrowRight className="concept-arrow" /><div className="concept concept-active"><span>02 <b>MINIDEV</b></span><h3>MiniDev</h3><p>Install only the runtimes you need and start services only when required.</p></div><ArrowRight className="concept-arrow" /><div className="concept"><span>03</span><h3>Result</h3><p>Cleaner environment, fewer unnecessary background processes.</p></div></div></section>

      <section className="specs section-grid" id="requirements"><div className="section-heading reveal"><span className="kicker">04 / DETAILS</span><h2>Small footprint.<br /><em>Clear boundaries.</em></h2></div><div className="spec-layout"><div className="spec-card reveal"><div className="spec-card-head"><span className="spec-symbol">M</span><span><b>MiniDev Beta</b><small>Application specification</small></span><span className="spec-version">v0.1.0</span></div>{[["Platform", "Windows"], ["Architecture", "x64"], ["Installer", "NSIS · ~3.8 MB"], ["Install scope", "Current user"], ["Administrator access", "Not required"]].map(([a, b]) => <div className="spec-row" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><div className="runtime-spec reveal reveal-delay"><div className="runtime-spec-title"><Server size={19} /><span><b>Managed runtimes</b><small>Downloaded when you need them</small></span></div><div className="runtime-line"><span>PHP</span><b>8.4.25</b><i>Portable</i></div><div className="runtime-line"><span>MySQL</span><b>8.4.11</b><i>Portable</i></div><div className="storage-note"><ShieldCheck size={16} /><p>Runtime storage<br /><strong>%LOCALAPPDATA%</strong></p></div><small className="fine-print">PHP and MySQL are downloaded on demand and are not bundled inside the MiniDev installer.</small></div></div></section>

      <section className="docs section-grid" id="documentation"><div className="section-heading reveal"><span className="kicker">05 / GET STARTED</span><h2>From install to<br /><em>first project.</em></h2><p>A clear path to a working local environment.</p></div><div className="docs-layout"><div className="steps reveal">{[["Install MiniDev", "Download the installer and complete the Windows installation."], ["Install PHP Runtime", "Open Runtime and choose Install PHP."], ["Install MySQL", "Open MySQL → Install Runtime → Initialize → Start MySQL."], ["Add Laravel Project", "Open Projects → Add Existing Project and choose your Laravel folder."], ["Start Project", "Click Start on the project you want to work on."], ["Open Project", "Click Open to launch the application in your browser."]].map(([title, text], i) => <div className="step" data-testid={`documentation-step-${i + 1}`} key={title}><span>{String(i + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><div className="database-panel reveal reveal-delay"><div className="panel-label"><Database size={15} /> DATABASE</div><h3>Keep the data layer close.</h3><p>Start MySQL first, then browse and manage your project data without leaving MiniDev.</p><ul><li>Start MySQL first</li><li>Select a database</li><li>Browse tables and records</li><li>Use SQL editor when needed</li><li>Import and export databases</li></ul></div></div></section>

      <section className="storage section-grid"><div className="storage-copy reveal"><span className="kicker">06 / ISOLATED BY DEFAULT</span><h2>Your runtime<br /><em>stays isolated.</em></h2><p>MiniDev keeps its managed runtimes and database data in a dedicated user location, separate from your global Windows PATH.</p><div className="storage-points"><span><Check size={14} /> Runtime is not added to global PATH</span><span><Check size={14} /> Database data stays separate</span><span><Check size={14} /> Reinstalling a runtime should not remove database data</span></div></div><div className="tree-card reveal reveal-delay" data-testid="runtime-storage-tree"><div className="tree-head"><FolderOpen size={16} /> Runtime storage</div><code><b>%LOCALAPPDATA%\com.minidev.app</b><br /><span>├── runtimes</span><br /><span>│   ├── php</span><br /><span>│   │   └── 8.4</span><br /><span>│   └── mysql</span><br /><span>│       └── 8.4</span><br /><span>├── mysql</span><br /><span>│   ├── data</span><br /><span>│   └── my.ini</span><br /><span>└── exports</span></code></div></section>

      <section className="beta-banner section-grid"><div className="beta-inner reveal"><div className="beta-icon"><Sparkles size={22} /></div><div><span className="beta-label">Beta Software</span><h2>MiniDev is currently in Beta.</h2><p>MiniDev is being actively tested. Features and behavior may change before the first stable release. Back up important development databases before testing beta releases.</p></div></div></section>
      <section className="requirements section-grid"><div className="section-heading reveal"><span className="kicker">07 / BEFORE YOU START</span><h2>Requirements, kept<br /><em>to the essentials.</em></h2></div><div className="requirement-list reveal reveal-delay">{["Windows 10 or Windows 11", "64-bit Windows", "Internet connection during the first PHP/MySQL runtime install", "Microsoft WebView2 Runtime, if not already available on Windows"].map((text, i) => <div key={text} data-testid={`requirement-${i + 1}`}><span>0{i + 1}</span><Check size={16} /><strong>{text}</strong></div>)}</div></section>
      <section className="faq section-grid" id="faq"><div className="section-heading reveal"><span className="kicker">08 / QUESTIONS</span><h2>Good to<br /><em>know.</em></h2></div><div className="faq-list reveal reveal-delay">{faqs.map(([question, answer], i) => <div className={activeFaq === i ? "faq-item active" : "faq-item"} key={question}><button data-testid={`faq-question-${i + 1}`} aria-expanded={activeFaq === i} onClick={() => setActiveFaq(activeFaq === i ? -1 : i)}><span>{question}</span><ChevronDown size={18} /></button><div className="faq-answer" data-testid={`faq-answer-${i + 1}`}><p>{answer}</p></div></div>)}</div></section>
      <section className="download-section section-grid" id="download"><div className="download-glow" /><div className="download-inner reveal"><span className="kicker">READY WHEN YOU ARE</span><h2>Ready to try<br /><em>MiniDev?</em></h2><p>Download the Windows Beta and start with only the runtime you need.</p><DownloadButton>Download MiniDev 0.1.0 <Download size={16} /></DownloadButton><div className="download-tags"><span>Windows x64</span><span>Beta</span><span>Installer ~3.8 MB</span></div></div></section>
    </main>
    <footer className="footer"><div><a data-testid="footer-brand-link" href="#overview" className="brand"><span className="brand-mark"><span /></span><span>MiniDev</span></a><p>Lightweight local development for Windows.</p></div><div className="footer-links">{[["Overview", "overview"], ["Features", "features"], ["Documentation", "documentation"], ["Download", "download"]].map(([label, id]) => <a data-testid={`footer-${id}-link`} href={`#${id}`} key={id}>{label}</a>)}</div><span className="copyright">© 2026 MiniDev</span></footer>
  </div>;
}

export default App;
